package com.college.sms.export;

import com.college.sms.entity.Marks;
import com.lowagie.text.*;
import com.lowagie.text.pdf.*;

import jakarta.servlet.http.HttpServletResponse;

import java.awt.Color;
import java.io.IOException;
import java.util.List;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class MarksPdfExporter {

    private final List<Marks> marksList;

    public MarksPdfExporter(List<Marks> marksList) {
        this.marksList = marksList;
    }

    public void export(HttpServletResponse response) throws IOException {

        Document document = new Document(PageSize.A4);

        PdfWriter.getInstance(document, response.getOutputStream());

        document.open();

        // ================= Title =================

        // ================= College Name =================

        Font collegeFont = FontFactory.getFont(
                FontFactory.HELVETICA_BOLD,
                24,
                new Color(0, 51, 153));

        Paragraph college = new Paragraph(
                "COLLEGE ERP SYSTEM",
                collegeFont);

        college.setAlignment(Element.ALIGN_CENTER);

        document.add(college);

// ================= Report Title =================

        Font reportFont = FontFactory.getFont(
                FontFactory.HELVETICA_BOLD,
                18,
                Color.DARK_GRAY);

        Paragraph report = new Paragraph(
                "MARKS REPORT",
                reportFont);

        report.setAlignment(Element.ALIGN_CENTER);

        document.add(report);

// ================= Date =================

        Font dateFont = FontFactory.getFont(
                FontFactory.HELVETICA,
                11,
                Color.GRAY);

        Paragraph date = new Paragraph(
                "Generated on : "
                        + java.time.LocalDate.now(),
                dateFont);

        date.setAlignment(Element.ALIGN_RIGHT);

        document.add(date);

        document.add(new Paragraph(" "));


        // ================= Summary =================

        Font summaryFont = FontFactory.getFont(
                FontFactory.HELVETICA,
                11,
                Color.DARK_GRAY);

        long passCount = marksList.stream()
                .filter(m -> "Pass".equalsIgnoreCase(m.getResult()))
                .count();

        long failCount = marksList.stream()
                .filter(m -> "Fail".equalsIgnoreCase(m.getResult()))
                .count();

        Paragraph summary = new Paragraph(
                "Total Records : " + marksList.size()
                        + "\nPassed : " + passCount
                        + "\nFailed : " + failCount
                        + "\nGenerated By : College ERP System"
                        + "\nGenerated At : "
                        + LocalDateTime.now().format(
                        DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss")),
                summaryFont);

        summary.setSpacingAfter(15);

        document.add(summary);
        // ================= Table =================

        PdfPTable table = new PdfPTable(8);

        table.setWidthPercentage(100);

        table.setSpacingBefore(10);

        table.setWidths(new float[]{
                1.2f,
                3.5f,
                2.5f,
                1.5f,
                1.5f,
                1.5f,
                1.5f,
                1.5f
        });

        writeHeader(table);

        writeData(table);

        document.add(table);
        document.add(new Paragraph(" "));

        Paragraph footer = new Paragraph(
                "This is a computer generated report from College ERP System.",
                FontFactory.getFont(
                        FontFactory.HELVETICA_OBLIQUE,
                        10,
                        Color.GRAY));

        footer.setAlignment(Element.ALIGN_CENTER);

        document.add(footer);

        document.add(new Paragraph(" "));

        Paragraph signature = new Paragraph(
                "Principal Signature\n\n________________________",
                FontFactory.getFont(
                        FontFactory.HELVETICA_BOLD,
                        11,
                        Color.BLACK));

        signature.setAlignment(Element.ALIGN_RIGHT);

        document.add(signature);

        document.add(new Paragraph(" "));

        Paragraph copyright = new Paragraph(
                "© 2026 College ERP System | Generated Automatically",
                FontFactory.getFont(
                        FontFactory.HELVETICA_OBLIQUE,
                        9,
                        Color.GRAY));

        copyright.setAlignment(Element.ALIGN_CENTER);

        document.add(copyright);

        document.close();
    }

    // ================= Header =================

    private void writeHeader(PdfPTable table) {

        PdfPCell cell = new PdfPCell();

        cell.setBackgroundColor(new Color(25, 118, 210));

        cell.setPadding(10);

        Font font = FontFactory.getFont(
                FontFactory.HELVETICA_BOLD);
        font.setSize(12);
        font.setColor(Color.WHITE);

        String[] headers = {

                "ID",
                "Student",
                "Subject",
                "Internal",
                "External",
                "Total",
                "Grade",
                "Result"

        };

        for (String header : headers) {

            cell.setPhrase(new Phrase(header, font));

            table.addCell(cell);

        }

    }

    // ================= Data =================

    private void writeData(PdfPTable table) {

        Font font = FontFactory.getFont(
                FontFactory.HELVETICA,
                11,
                Color.BLACK);

        boolean alternate = false;

        for (Marks marks : marksList) {

            Color rowColor = alternate
                    ? new Color(245, 245, 245)
                    : Color.WHITE;

            addCell(table, String.valueOf(marks.getId()), font, rowColor);

            addCell(table,
                    marks.getStudent().getFirstName() + " "
                            + marks.getStudent().getLastName(),
                    font,
                    rowColor);

            addCell(table,
                    marks.getSubject(),
                    font,
                    rowColor);

            addCell(table,
                    String.valueOf(marks.getInternalMarks()),
                    font,
                    rowColor);

            addCell(table,
                    String.valueOf(marks.getExternalMarks()),
                    font,
                    rowColor);

            addCell(table,
                    String.valueOf(marks.getTotalMarks()),
                    font,
                    rowColor);

            addCell(table,
                    marks.getGrade(),
                    font,
                    rowColor);

            addCell(table,
                    marks.getResult(),
                    font,
                    rowColor);

            alternate = !alternate;
        }
    }
    private void addCell(PdfPTable table,
                         String value,
                         Font font,
                         Color backgroundColor) {

        PdfPCell cell = new PdfPCell(new Phrase(value, font));

        cell.setBackgroundColor(backgroundColor);

        cell.setPadding(6);

        table.addCell(cell);

    }
}